name: Deploy

on:
  workflow_call:
    secrets:
      rockeset-token:
        required: true
      access_key:
        required: true
      secret_access:
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ROCKESET_API_KEY: ${{ secrets.rockeset-token }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: env
        run: echo "env"
        env:
          #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access }}
