name: Deploy serverless

on:
  workflow_call:
    inputs:
      env_stage:
        required: true
        type: string
      aws_region:
        required: true
        type: string
    secrets:
      aws_access_key:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy-serverless:
    name: deploy serverless
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage=${{ inputs.env_stage }} --region=${{ inputs.aws_region }} --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
