name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prueba
        run: echo ${{ secrets.ROCKESET_API_KEY }}   