name: Deploy serverless

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      env_stage:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      url_zulu:
        required: false
        type: string

jobs:
  deploy-serverless:
    name: ${{ inputs.env_stage }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_stage }}
      url: ${{ inputs.url_zulu }}

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage=${{ inputs.env_stage }} --region=${{ inputs.aws_region }} --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
