name: Deploy

on:
  workflow_call:
    secrets:
      rockeset-token:
        required: true
      access_key:
        required: true
      secret_access:
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ROCKESET_API_KEY: ${{ secrets.rockeset-token }}
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{ secrets.access_key }} --secret ${{ secrets.secret_access  }} --aws-profile zulu
      - name: Deploy to AWS
        run: sls deploy --stage=dev --region=us-east-1
