name: release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: zuluapp/zulu-workflows/.github/workflows/release.yml@main
    with:
      env_version_scheme: minor
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

# minor
# major
# patch
# norelease
