name: Slack Notification

on:
  workflow_call:

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  slackNotification:
    name: Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ secrets.SLACK_MESSAGE }}
          SLACK_TITLE: ${{ secrets.SLACK_TITLE }}
          SLACK_WEBHOOK: $SLACK_WEBHOOK
