name: Slack Notification

on:
  workflow_call:
    secrets:
      slack_webhook:
        required: true

jobs:
  slackNotification:
    name: Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ci-cd-request
          SLACK_USERNAME: zulu-bot
          SLACK_ICON_EMOJI: ":yeeaahhh:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Success deploy :rocket:"
          SLACK_TITLE: status
          SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
