name: Linter

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: yarn

      - name: Run test-coverage
        run: npm run test-coverage
